### ISSUE TITLE
RPA.Email.Exchange. Error with `Wait For Message` keyword filtering

### ISSUE THREAD

**Issue by mikahanninen** [robocorp/rpaframework#418] opened 2022-03-09 12:44 UTC
https://forum.robocorp.com/t/rpa-email-exchange-wait-for-message-error/1530

This bug is to be fixed along with the related issue https://github.com/robocorp/rpaframework/issues/410

**Comment by pradnair** [comment] 2022-03-09 13:35
Hi Mika, thanks for looking into the bug, I suspect there might be a logical issue in the code here,
Say I send a mail t minutes ago and mail received in Inbox. If I check for it after 5 minutes , the right_now time is t+5 minutes and I will not receive the message. In my library I have removed  'datetime_received__gte=right_now' to get the message . Please check and let me know if the hypothesis is correct. 

        tz = EWSTimeZone.localzone()
        right_now = tz.localize(EWSDateTime.now())  # pylint: disable=E1101
        while time.time() < end_time:
            items = self.account.inbox.filter(  # pylint: disable=E1101
                **filter_dict, datetime_received__gte=right_now

**Comment by mikahanninen** [comment] 2022-03-10 14:12
@pradnair I think the situation you described does not apply to the concept of waiting for the message if the message already exists in the mailbox. I guess you should be looking for the message (maybe from unread messages) and then maybe notice that there is no need to wait as you already have the email ?

Or do you see that this keyword should have a parameter that could give a starting time for the wait, ie. not now but some time into the past?

**Comment by pradnair** [comment] 2022-03-10 15:59
@mikahanninen, 
IMHO, If you look at the implementation of wait_for_message in RPA.Email.ImapSmtp it filters the source_folder based on the criterion and returns if the message available. If not yet reached it will sleep for the interval time and rechecks until the timeout period. This seems a more logical approach to me as this one keyword will suffice for both cases. Saves one the trouble of List Messsage and then wait for it if not available.

**Comment by pradnair** [comment] 2022-03-11 10:30
@mikahanninen  , just realised this bug is a duplicate of https://github.com/robocorp/rpaframework/issues/377

**Comment by mikahanninen** [comment] 2022-03-11 11:05
Problem with exception is that I have not been able to replicate it. I need to have **conda.yaml** defining the environment where this problem occurs.

`AttributeError: 'EWSTimeZone' object has no attribute 'localize'`

**Comment by mikahanninen** [comment] 2022-03-11 13:43
I think I found the reason and there will be fix in the next release

**Closed** 2022-03-11 14:14 UTC
Labels: bug
