### ISSUE TITLE
Excel.Files Open workbook gives file not found if it contains VB project (even empty code)

### ISSUE THREAD

**Issue by Harm10** [robocorp/rpaframework#563] opened 2022-06-23 12:36 UTC
I am experiencing problems with opening an xls file through open workbook. This file can be read normally through Excel itself.
If I convert the file to xlsx no problems. I noticed the xls file contains VB project remnants but the module code is empty (so there is a module reference there). If I save that file again and loose the empty VB project the opening problem disappears.

I am on rpaframework 10.9.3 and rpaframework-core 6.4.0

At least I would expect another error message than file does not exist or has wrong extension.

**Comment by cmin764** [comment] 2022-06-29 07:55
Hi, can you try please with latest `rpaframework==15.1.4` and even provide to us an example Excel file so we can replicate on our side as well?

**Comment by Harm10** [comment] 2022-07-03 10:40
I will test with latest 15.1.4 and report back.

**Comment by cmin764** [comment] 2022-07-08 14:41
I will close this one since there were no any news here, please re-open if you can still reproduce the issue with an attached example and code snippet reproducing the error. Thank you!

**Closed by cmin764** 2022-07-08 14:41 UTC
Labels: bug

**Comment by Harm10** [comment] 2022-07-31 11:43
Still have not found the time within a live environment to experiment with this. Planning this for coming week. Will report back (and reopen) when I have additional information.

**Comment by cmin764** [comment] 2022-08-01 11:34
Thank you @Harm10 , meanwhile feel free to use our [forum](https://forum.robocorp.com/c/robocorp-build/rpa-framework/18) for similar issues or reporting a new one.

**Comment by Harm10** [comment] 2022-12-19 16:54
I tried several times to reproduce this problem to no avail. Left my package versions as they are. Weird but true. If it occurs again I will update this report.
